### PR TITLE
Support optionally restricting controller to a namespace

### PR DESCRIPTION
**Pull request by ddseapy**

### CODE REVIEW

**Review by wallyqs — APPROVED** [review]
LGTM

**Comment by ddseapy** [comment]
looks like it failed CI build, i'm surprised i didn't see this when doing a make on the 3 components and a make on their `-docker` variants.

**Comment by wallyqs** [comment]
will take a look, maybe we need to fix the GitHub action... /cc @variadico

**Comment by ddseapy** [comment]
the ci looks like it's doing a `make build`, but if i do a `make clean` followed by a `make build` i'm getting:
```
go build -race -o jetstream-controller \
	-ldflags "-X main.BuildTime=2021-07-07T17:28:55+0000 -X main.GitInfo=support_restricting_namespace-b704fad -X main.Version=version-not-set" \
	github.com/nats-io/nack/cmd/jetstream-controller
go build -race -o nats-server-config-reloader \
	-ldflags "-X main.BuildTime=2021-07-07T17:28:55+0000 -X main.GitInfo=support_restricting_namespace-b704fad -X main.Version=version-not-set" \
	github.com/nats-io/nack/cmd/nats-server-config-reloader
go build -race -o nats-boot-config \
	-ldflags "-X main.BuildTime=2021-07-07T17:28:55+0000 -X main.GitInfo=support_restricting_namespace-b704fad -X main.Version=version-not-set" \
	github.com/nats-io/nack/cmd/nats-boot-config
```
and it generates the binaries successfully.

looking more closely at the code now to see the difference

**Comment by ddseapy** [comment]
I had modified generated files, which I should not have done.  Put up an MR to revert the generated file changes (https://github.com/nats-io/nack/pull/32).

The diff between this commit and the previous one before the generated files were changed is: https://github.com/ddseapy/nack/compare/32a9813..7f9d87f

**Pull request merged**
