### PR TITLE
Provide e2e testing based on kuttl

### LINKED ISSUE #59: Add e2e tests

### PR DESCRIPTION
**Pull request by 1995parham**
Provide e2e testing using [kuttl](https://kuttl.dev/). Closes #59

### CODE REVIEW

**Comment by 1995parham** [comment]
- provide NATS helm chart values
- Deploy NACK and connect it to the deployed Jetstream cluster
- Create an stream
- Deploy nats-box pod to validate stream creation

**Comment by 1995parham** [comment]
@wallyqs What do you think about the structure? Right now, it checks stream creation only. If you agree I can create the required Github actions too and then add more cases.

Only issue I need to track down is RBAC. NACK helm chart installs RBAC but they are not removed by `helm uninstall` so we get error when we run tests multiple times.

**Comment by wallyqs** [comment]
I think structure looks great, it is easy to follow what is happening in each of the steps.

**Comment by 1995parham** [comment]
I think we can consider this finish for at least checking the stream creation. Here is the workflow result for e2e testing.

https://github.com/1995parham/nack/actions/runs/7170032922/job/19521815874

**Review by wallyqs — APPROVED** [review]
LGTM! 🙌

**Pull request merged**
