### PR TITLE
[FIX] consumer from headers-only to deliver bodies

### PR DESCRIPTION
**Pull request by ramonberrutti**
New jsm.go version is requiered: https://github.com/nats-io/jsm.go/releases/tag/v0.1.2

### CODE REVIEW

**Comment by ramonberrutti** [comment]
c/c @ripienaar

**Comment by Jarema** [comment]
@ramonberrutti This is stil an issue, right?

**Comment by ramonberrutti** [comment]
@Jarema yes

**Review by Jarema — APPROVED** [review]
LGTM!

**Pull request merged**
