### PR TITLE
Add servers, creds and nkey options to nack

### PR DESCRIPTION
**Pull request by JackZxj**
Hi, this pr is for #21 .

NATS is a so amazing project! So I want to do something to make it better. I don’t know if my understanding is correct, so I drew a picture to express my thoughts:

image

What's different:

Add a `servers` option for Stream/StreamTemplate and Consumer crd. It's optional and will be an empty array by default. When you set this option, the controller will create a new nats connection and then initialize a jsm client to create Stream/StreamTemplate or Consumer.

```bash
$ kubectl logs jetstream-controller-65d5898bb7-9r4rb -f
# without servers option
I0304 08:04:14.386280       1 event.go:282] Event(v1.ObjectReference{Kind:"Stream", Namespace:"default", Name:"testnoserver00", UID:"e48551cf-6101-4e1f-813a-637b4d711605", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21314662", FieldPath:""}): type: 'Normal' reason: 'Creating' Creating stream "testnoserver00"
I0304 08:04:14.474232       1 event.go:282] Event(v1.ObjectReference{Kind:"Stream", Namespace:"default", Name:"testnoserver00", UID:"e48551cf-6101-4e1f-813a-637b4d711605", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21314663", FieldPath:""}): type: 'Normal' reason: 'Created' Created stream "testnoserver00"

I0304 08:07:27.259351       1 event.go:282] Event(v1.ObjectReference{Kind:"Consumer", Namespace:"default", Name:"testnoserver00", UID:"1cd08dae-bb7c-41aa-863d-6306a352bcfd", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21315279", FieldPath:""}): type: 'Normal' reason: 'Creating' Creating consumer "testnoserver00" on stream "testnoserver00"
I0304 08:07:27.340657       1 event.go:282] Event(v1.ObjectReference{Kind:"Consumer", Namespace:"default", Name:"testnoserver00", UID:"1cd08dae-bb7c-41aa-863d-6306a352bcfd", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21315280", FieldPath:""}): type: 'Normal' reason: 'Created' Created consumer "testnoserver00" on stream "testnoserver00"

# with servers option
I0304 08:13:37.694530       1 event.go:282] Event(v1.ObjectReference{Kind:"Stream", Namespace:"default", Name:"testserver00", UID:"3629f0b3-522d-4286-99aa-71dbe8c9fc8e", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21316506", FieldPath:""}): type: 'Normal' reason: 'Creating' Creating stream "testserver00"
I0304 08:13:37.696927       1 event.go:282] Event(v1.ObjectReference{Kind:"Stream", Namespace:"default", Name:"testserver00", UID:"3629f0b3-522d-4286-99aa-71dbe8c9fc8e", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21316506", FieldPath:""}): type: 'Normal' reason: 'Connecting' Connecting to new nats-servers
I0304 08:13:37.958991       1 event.go:282] Event(v1.ObjectReference{Kind:"Stream", Namespace:"default", Name:"testserver00", UID:"3629f0b3-522d-4286-99aa-71dbe8c9fc8e", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21316507", FieldPath:""}): type: 'Normal' reason: 'Created' Created stream "testserver00"

I0304 08:17:10.385516       1 event.go:282] Event(v1.ObjectReference{Kind:"Consumer", Namespace:"default", Name:"testserver00", UID:"1c5afc4d-703f-4cdb-aaba-cfc243c23f5d", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21317215", FieldPath:""}): type: 'Normal' reason: 'Creating' Creating consumer "testserver00" on stream "testserver00"
I0304 08:17:10.391586       1 event.go:282] Event(v1.ObjectReference{Kind:"Consumer", Namespace:"default", Name:"testserver00", UID:"1c5afc4d-703f-4cdb-aaba-cfc243c23f5d", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21317215", FieldPath:""}): type: 'Normal' reason: 'Connecting' Connecting to new nats-servers
I0304 08:17:10.843949       1 event.go:282] Event(v1.ObjectReference{Kind:"Consumer", Namespace:"default", Name:"testserver00", UID:"1c5afc4d-703f-4cdb-aaba-cfc243c23f5d", APIVersion:"jetstream.nats.io/v1beta1", ResourceVersion:"21317216", FieldPath:""}): type: 'Normal' reason: 'Created' Created consumer "testserver00" on stream "testserver00"
```

### CODE REVIEW

**Comment by wallyqs** [comment]
Thanks a lot for documenting this and the PR. I think the use case sounds good, and generally LGTM, but will try to take a proper look next week.

**Comment by JackZxj** [comment]
> Thanks a lot for documenting this and the PR. I think the use case sounds good, and generally LGTM, but will try to take a proper look next week.

Hello, how is it going? @wallyqs

**Comment by wallyqs** [comment]
@JackZxj apologies, it has been a busy couple of weeks shipping the server and now the Go client, I will try to check today and merge. Thanks again.

**Comment by JackZxj** [comment]
My pleasure. If anything is wrong, please contact me. I'm happy to contribute to this project!

**Comment by JackZxj** [comment]
Hi, @wallyqs . 

I added two other options to NACK. With these two options, the controller can connect to the new jetstream in different authentication ways.

**Comment by PacoDu** [comment]
Hi, thanks  for your work @JackZxj !
We are also waiting for this feature, can we know if it will be merged soon or if there is any issue with this PR ?

**Comment by wallyqs** [comment]
We finally merged this as part of #42, thanks for the contribution. Apologies with the delay in integrating this into the main repo...
There is now an accounts CRD where the creds can be stored so that they are fetched from the API server:

```
---
apiVersion: jetstream.nats.io/v1beta2
kind: Account
metadata:
  name: a
spec:
  name: a
  servers:
  - nats://nats:4222
  tls:
    secret:
      name: nack-a-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
```

```yaml
---
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
metadata:
  name: foo3
spec:
  name: foo3
  subjects: ["foo3", "foo3.>"]
  storage: file
  replicas: 1
  account: a
```

**Comment by JackZxj** [comment]
> We finally merged this as part of #42, thanks for the contribution. Apologies with the delay in integrating this into the main repo... There is now an accounts CRD where the creds can be stored so that they are fetched from the API server:
> 
> ```yaml
> ---
> apiVersion: jetstream.nats.io/v1beta2
> kind: Account
> metadata:
>   name: a
> spec:
>   name: a
>   servers:
>   - nats://nats:4222
>   tls:
>     secret:
>       name: nack-a-tls
>     ca: "ca.crt"
>     cert: "tls.crt"
>     key: "tls.key"
> ```
> 
> ```yaml
> ---
> apiVersion: jetstream.nats.io/v1beta2
> kind: Stream
> metadata:
>   name: foo3
> spec:
>   name: foo3
>   subjects: ["foo3", "foo3.>"]
>   storage: file
>   replicas: 1
>   account: a
> ```

I am so glad to contribute to this project~

**Pull request closed without merging**
